---
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    reference_docx: ./resources/aog_word_style.docx
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
pagenumber: 1
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
title: "The Title"
author:
- affiliation: University of Oregon, Sociology
  name: Aaron Gullickson
- affiliation: Some Research University
  name: My co-author
keywords: keywords
thanks: Thanks to people and stuff
abstract: This is a test abstract
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("../../analysis/output/analytical_data.RData")
```

# Introduction
This research is designed to answer the question "What kinds of demographic characteristics are associated with dis/belief in climate change?". This project reinvestigates past research that has attempted to identify particualr demographic charicteristics that are associated with disbelief in climate change. Previous research has found that white conservative men are more likley to deny the occurrence of climate chagne (McCright and Dunlap 2011). This research investigates the current state of climate belief in the United States as a way to analyze potential changes in the sociodemogrpahic profiles of those who dis/believe in climate change. 

# Data and Methods
Data were collected across nine years (2008-2017), also referred to as waves, through the use of self-administered web-based surveys by the Yale Program on Climate Change Communication. Surveys were administered on a yearly basis in 2008, while surverys were administed on a twice-yearly basis from 2010 to 2017. The dataset contains a total of 20,024 responses (N = 24,024). The codebook notes that "Prospective members were recruited using a combination of random digit dial and address-based sampling techniques that cover virtually all (noninstitutional) resident phone numbers and addresses in the United States."

# Results

# Conclusions

# References
